FROM node:22-alpine
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install
COPY . .
EXPOSE 5173
# Exponemos Vite en todas las interfaces de red para que sea accesible fuera de Docker
CMD ["pnpm", "run", "dev", "--host"]