FROM node:22-alpine
WORKDIR /app
# Instalamos pnpm globalmente en el contenedor
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install
COPY . .
EXPOSE 3000
CMD ["pnpm", "start"]